=== fundor333/TesinaReti/Documentazione/esempio.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="lettera">

<xs:complexType>
<xs:sequence>
	<xs:element name="mittente" type="xs:string"></xs:element>
	<xs:element name="data" type="xs:date"></xs:element>
	<xs:element name="destinatario" type="xs:string"></xs:element>
	<xs:element name="oggetto" type="xs:string"></xs:element>
	<xs:element name="forma_cortesia" type="xs:string"></xs:element>
	<xs:element name="corpo" minOccurs="1">
		<xs:complexType><xs:sequence><xs:element name="paragrafo" type="xs:string"></xs:element></xs:sequence></xs:complexType>
		</xs:element>
	<xs:element name="chiusura" type="xs:string"></xs:element>
	<xs:element name="firma" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType></xs:element>

</xs:schema>

=== fundor333/TesinaReti/Documentazione/esempio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="esempio.css"?>
<lettera xsi:noNamespaceSchemaLocation="esempio.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<mittente>Romeo Rossi</mittente>
<data>2012-09-28</data>
<destinatario>Giulietta Verdi</destinatario>
<oggetto>Riunione operativa</oggetto>
<forma_cortesia>Egregia Dott.ssa Verdi </forma_cortesia>
<corpo>
<paragrafo>come da accordi telefonici, indico la riunione operativa per il 3 ottobre 2012 alle ore 10:00. Prego di portare tutti i documenti relativi al progetto
</paragrafo>
</corpo>
<chiusura>Cordiali Saluti
</chiusura>
<firma>Romeo Rossi
</firma>
</lettera>
